module.exports = {

  // 场景集合
  scene: [{
    type: 1,
    name: 'MVVM应用'
  }, {
    type: 2,
    name: '集成客户端应用'
  }, {
    type: 3,
    name: 'SSR应用'
  }, {
    type: 4,
    name: '中台应用'
  }, {
    type: 5,
    name: '博客网站应用'
  }, {
    type: 6,
    name: '服务侧应用'
  }, {
    type: 7,
    name: '移动侧APP'
  }, {
    type: 8,
    name: 'PC侧APP'
  }],

  // 数据集合
  data: [{
    // 所属场景
    sceneType: 1,
    // 模板名称
    name: 'Vue',
    // 模板描述
    desc: '',
    // 模板安装或下载命令
    install: '',
    // 模板预安装命令
    preInstall: '',
  }, {
    sceneType: 1,
    name: 'React',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 1,
    name: 'Angular',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 1,
    name: 'Vue技术栈',
    desc: 'ElementUI + Sass + Vue + VueRouter + Vuex + Axios  + Webpack',
    install: '',
    preInstall: '',
  }, {
    sceneType: 1,
    name: 'React技术栈',
    desc: 'AntDesign + Less + React + ReactRouter + Redux + ReduxSaga +  Fetch + Webpack',
    install: '',
    preInstall: '',
  }, {
    sceneType: 2,
    name: 'Dva',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 2,
    name: 'Umi',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 3,
    name: 'Nuxt',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 3,
    name: 'Next',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 4,
    name: 'AntDesignPro',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 5,
    name: 'VuePress',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 5,
    name: 'Hexo',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 6,
    name: 'Express',
    desc: '一般用于中小型项目服务端开发或者中间层开发',
    install: '',
    preInstall: '',
  }, {
    sceneType: 6,
    name: 'Koa',
    desc: 'Express替代版',
    install: '',
    preInstall: '',
  }, {
    sceneType: 6,
    name: 'Egg',
    desc: '企业级开发框架',
    install: '',
    preInstall: '',
  }, {
    sceneType: 6,
    name: 'Nest',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 7,
    name: 'ReactNative',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 7,
    name: 'Weex',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 7,
    name: 'PWA',
    desc: '',
    install: '',
    preInstall: '',
  }, {
    sceneType: 8,
    name: 'Electron',
    desc: '',
    install: '',
    preInstall: '',
  }, ]
}
